services:
  db:
    image: mysql:8.0
    restart: always
    container_name: news_app-db
    environment:
      MYSQL_DATABASE: news_app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: news_user
      MYSQL_PASSWORD: news_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: news_app-web
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles   # <— persistent static files volume
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: news_app
      MYSQL_USER: news_user
      MYSQL_PASSWORD: news_pass
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      DOCKER_ENV: "true"

  nginx:
    image: nginx:latest
    container_name: news_app-nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  db_data:
  static_volume:
